trigger:
- master
 
pool:
  vmImage: 'vs2017-win2016'
 
steps:
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
    ArtifactName: 'arti'
    publishLocation: 'Container'
