resources:
  repositories:
  - repository: react-app-test-automation
    type: github
    endpoint: LayMui
    name: LayMui/react-app-test-automation
 
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm start &
  displayName: 'npm install and start the server running at localhost:3000'
  
- checkout: react-app-test-automation
- script: |
    npm install
    npm test
  workingDirectory: ($Build.SourcesDirectory)/ ##your repo name 
  displayName: 'npm install and my end to end automation test'

 
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)'
#     ArtifactName: 'arti'
#     publishLocation: 'Container'
 
