resources:
  repositories:
  - repository: react-app-test-automation
    type: github
    endpoint: LayMui
    name: LayMui/react-app-test-automation
 
trigger:
- master

stages:
  -   stage: Build
      displayName: Build
      jobs:
        -   job: Build
            pool:
              vmImage: 'ubuntu-latest' 

            steps:
            - checkout: self
            - task: NodeTool@0
              inputs:
                versionSpec: '10.x'
              displayName: 'Install Node.js'

            - script: |
                npm install
                npm start &
              workingDirectory: $(Build.SourcesDirectory)/react-app-typescript
              displayName: 'npm install and start the server running at localhost:3000'
            
            - checkout: react-app-test-automation
            - script: |
                npm install
                npm test
              workingDirectory: $(Build.SourcesDirectory)/react-app-test-automation
              displayName: 'npm install and my end to end automation test in chrome'

            - checkout: react-app-test-automation
            - task: CopyFiles@2
              inputs:
                sourceFolder: $(Build.SourcesDirectory)/react-app-test-automation
                contents: |
                  target/site/serenity/**
                TargetFolder: $(Build.ArtifactStagingDirectory)
            - task: PublishPipelineArtifact@1
              inputs:
                targetPath: $(Build.ArtifactStagingDirectory)
                artifactName: target-folder

  -   stage: DevDeploy
      dependsOn: Build
      displayName: DevDeploy
      jobs:
        -   job: DevDeploy
            pool:
              vmImage: 'ubuntu-latest' 
            steps:
              - checkout: self
              - task: NodeTool@0
                inputs:
                  versionSpec: '10.x'
                displayName: 'Install Node.js'

              - script: |
                  npm install
                  npm start &
                workingDirectory: $(Build.SourcesDirectory)/react-app-typescript
                displayName: 'npm install and start the server running at localhost:3000'
              
              - checkout: react-app-test-automation
              - script: |
                  npm install
                  npm test
                workingDirectory: $(Build.SourcesDirectory)/react-app-test-automation
                displayName: 'npm install and my end to end automation test in chrome in dev'

              - checkout: react-app-test-automation
              - task: CopyFiles@2
                inputs:
                  sourceFolder: $(Build.SourcesDirectory)/react-app-test-automation
                  contents: |
                    target/site/serenity/**
                  TargetFolder: $(Build.ArtifactStagingDirectory)
              - task: PublishPipelineArtifact@1
                inputs:
                  targetPath: $(Build.ArtifactStagingDirectory)
                  artifactName: target-folder-dev

                    
  