resources:
  repositories:
  - repository: react-app-test-automation
    type: github
    endpoint: LayMui
    name: LayMui/react-app-test-automation
 
trigger:
- master


stages:
  -   stage: Build
      displayName: Build
      jobs:
        -   job: Build
            pool:
              vmImage: 'ubuntu-latest'

            steps:
            - checkout: self
            - task: NodeTool@0
              inputs:
                versionSpec: '10.x'
              displayName: 'Install Node.js'

            - script: |
                npm install
                npm start &
              workingDirectory: $(Build.SourcesDirectory)/react-app-typescript
              displayName: 'npm install and start the server running at localhost:3000'
            
            - checkout: react-app-test-automation
            - script: |
                npm install
                npm test
              workingDirectory: $(Build.SourcesDirectory)/react-app-test-automation
              displayName: 'npm install and my end to end automation test in chrome'

            - checkout: react-app-test-automation
            - task: CopyFiles@2
              inputs:
                sourceFolder: $(Build.SourcesDirectory)/react-app-test-automation
                contents: |
                  target/site/serenity/**
                TargetFolder: $(Build.ArtifactStagingDirectory)
            - task: PublishPipelineArtifact@1
              inputs:
                targetPath: $(Build.ArtifactStagingDirectory)
                artifactName: target-folder
              
        - job: create_test_reports_web
          displayName: Create web with test reports
          pool:
            vmImage: 'ubuntu-latest'
          dependsOn: Build
          steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'current'
                  artifactName: 'target-folder'
                  targetPath: '$(Pipeline.Workspace)'
      
              - task: AzureCLI@2
                inputs:
                  azureSubscription: 'Azure subscription 1 - demo'
                  scriptType: 'pscore'
                  scriptLocation: 'inlineScript'
                  inlineScript: 'az webapp delete -n react-app-todo -g demo'
                 
              - task: AzureCLI@2
                inputs:
                  azureSubscription: 'Azure subscription 1 - demo'
                  scriptType: 'pscore'
                  scriptLocation: 'inlineScript'
                  inlineScript: 'az webapp up -n react-app-todo -g demo -l southeastasia -p demo --html'
                  workingDirectory: '$(Pipeline.Workspace)/target/site/serenity'
              
       
  -   stage: DevDeploy
      dependsOn: Build
      displayName: DevDeploy
      jobs:
        -   deployment: DevDeploy
            environment: Dev
            strategy: 
              runOnce:
                deploy:
                  pool:
                    vmImage: 'ubuntu-latest' 
                  steps:
                    - checkout: self
                    - task: NodeTool@0
                      inputs:
                        versionSpec: '10.x'
                      displayName: 'Install Node.js'

                    - script: |
                        npm install
                        npm start & 
                      workingDirectory: $(Build.SourcesDirectory)/react-app-typescript
                      displayName: 'npm install and start the server running at localhost:3000'
              
                    - checkout: react-app-test-automation
                    - script: |
                        npm install
                        npm test
                      workingDirectory: $(Build.SourcesDirectory)/react-app-test-automation
                      displayName: 'npm install and my end to end automation test in chrome in dev'

                    - checkout: react-app-test-automation
                    - task: CopyFiles@2
                      inputs:
                        sourceFolder: $(Build.SourcesDirectory)/react-app-test-automation
                        contents: |
                          target/site/serenity/**
                        TargetFolder: $(Build.ArtifactStagingDirectory)
                    - task: PublishPipelineArtifact@1
                      inputs:
                        targetPath: $(Build.ArtifactStagingDirectory)
                        artifactName: target-folder-dev

  -   stage: QADeploy
      dependsOn: Build
      displayName: QADeploy
      jobs:
        -   deployment: QADeploy
            environment: QA
            strategy: 
              runOnce:
                deploy:
                  pool:
                    vmImage: 'ubuntu-latest' 
                  steps:
                    - checkout: self
                    - task: NodeTool@0
                      inputs:
                        versionSpec: '10.x'
                      displayName: 'Install Node.js'

                    - script: |
                        npm install
                        npm start &
                      workingDirectory: $(Build.SourcesDirectory)/react-app-typescript
                      displayName: 'npm install and start the server running at localhost:3000'
          
                    - checkout: react-app-test-automation
                    - script: |
                        npm install
                        npm test
                      workingDirectory: $(Build.SourcesDirectory)/react-app-test-automation
                      displayName: 'npm install and my end to end automation test in chrome in qa'

                    - checkout: react-app-test-automation
                    - task: CopyFiles@2
                      inputs:
                        sourceFolder: $(Build.SourcesDirectory)/react-app-test-automation
                        contents: |
                          target/site/serenity/**
                        TargetFolder: $(Build.ArtifactStagingDirectory)
                    - task: PublishPipelineArtifact@1
                      inputs:
                        targetPath: $(Build.ArtifactStagingDirectory)
                        artifactName: target-folder-qa

  -   stage: ProdDeploy
      dependsOn: 
        - DevDeploy
        - QADeploy
      displayName: ProdDeploy
      jobs:
        -   deployment: ProdDeploy
            environment: Prod
            strategy: 
              runOnce:
                deploy:
                  pool:
                    vmImage: 'ubuntu-latest' 
                  steps:
                    - checkout: self
                    - task: NodeTool@0
                      inputs:
                        versionSpec: '10.x'
                      displayName: 'Install Node.js'

                    - script: |
                        npm install
                        npm start &
                      workingDirectory: $(Build.SourcesDirectory)/react-app-typescript
                      displayName: 'npm install and start the server running at localhost:3000'
      
                    - checkout: react-app-test-automation
                    - script: |
                        npm install
                        npm test
                      workingDirectory: $(Build.SourcesDirectory)/react-app-test-automation
                      displayName: 'npm install and my end to end automation test in chrome in prod'

                    - checkout: react-app-test-automation
                    - task: CopyFiles@2
                      inputs:
                        sourceFolder: $(Build.SourcesDirectory)/react-app-test-automation
                        contents: |
                          target/site/serenity/**
                        TargetFolder: $(Build.ArtifactStagingDirectory)
                    - task: PublishPipelineArtifact@1
                      inputs:
                        targetPath: $(Build.ArtifactStagingDirectory)
                        artifactName: target-folder-prod
                            
  